### ISSUE TITLE
Use of this project?

### ISSUE THREAD

**Issue by OhSoGood** [ncorgan/SoapyVOLKConverters#4]
Hi,

Could you give more insight about what this project does (I am a long-time user of Soapy to use on USRP and LimeSDR) ? Is that a kind of extra-layer between the SDR and Soapy to convert on the fly the incoming I/Q in other formats? If so, how to use it, and how does it compare to directly using SIMD instructions (or maybe it is the same?) ?

Thank you !

**Comment by ncorgan** [comment]
Hi, that's correct. A couple Soapy modules (not sure which) use SoapySDR's converters internally to convert to/from the device's native streaming format. This module overrides some of the default converters with more efficient ones implemented in VOLK. Once you build and install this module, the change will happen automatically.

Hopefully this clears things up, I didn't realize the README didn't have a description.
